In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt

I transformed the missing data (nan) with mean (for real type data) and median (for integer type data)

In [2]:
df_train = pd.read_csv('./4.train_without_outlier.csv')
df_test = pd.read_csv('./4.test_without_outlier.csv')

In [3]:
print(df_train.shape)
print(df_test.shape)

(19337, 22)
(6000, 21)


In [4]:
df_merge_data = pd.concat([df_train,df_test])

In [5]:
df_merge_data.dtypes

job_level                                  int64
job_duration_in_current_job_level        float64
person_level                               int64
job_duration_in_current_person_level     float64
job_duration_in_current_branch           float64
Employee_type                              int64
gender                                     int64
age                                        int64
marital_status_maried(Y/N)                 int64
number_of_dependences                    float64
Education_level                            int64
GPA                                      float64
year_graduated                             int64
job_duration_from_training               float64
branch_rotation                          float64
job_rotation                             float64
assign_of_otherposition                  float64
annual leave                             float64
sick_leaves                              float64
Last_achievement_%                       float64
Achievement_above_10

In [6]:
null_col = df_merge_data.columns[df_merge_data.isna().any()]
null_df = df_merge_data[null_col].isna().sum().rename('missing rows').to_frame()
null_df['percentage'] = round(null_df['missing rows'] / df_merge_data.shape[0] * 100, 3)
null_df['percentage'] = null_df['percentage'].astype('str')

null_df.sort_values('missing rows', ascending=False).style.background_gradient('Blues')

# GPA

In [7]:
print(df_merge_data['GPA'].unique())

[ nan 2.83 3.02 3.14 3.08 3.19 3.13 3.21 2.85 2.79 3.27 3.12 3.33 3.24
 3.71 3.03 2.82 2.89 3.65 3.25 3.56 3.59 3.1  3.16 2.73 3.09 3.5  2.76
 2.78 2.97 3.26 3.15 3.3  2.98 3.31 3.52 2.77 2.69 2.9  2.96 3.06 2.86
 2.81 3.58 2.62 3.23 2.93 3.54 2.91 3.01 3.32 3.   3.2  3.7  2.87 3.05
 3.07 3.17 3.62 3.04 3.37 3.64 3.22 3.28 3.11 2.64 2.95 2.68 3.46 2.71
 3.53 3.38 3.44 3.74 2.75 2.72 3.4  3.42 2.92 3.18 2.37 3.51 3.68 2.84
 3.36 3.34 3.45 3.41 3.57 3.39 3.35 3.43 3.29 3.49 2.8  3.67 3.47 3.55
 3.48 3.85 2.67 3.6  3.61 3.69 2.99 2.94 3.77 2.7  3.8  3.78 3.81 3.73
 3.63 2.88 3.79 3.9  3.66 3.82 2.66 2.6  2.74 3.91 2.59 2.57 3.75 3.76
 2.53 2.54 2.55 2.63 2.51 2.5  2.56 2.65 2.45 3.92 2.25 3.89 2.42 3.84
 3.72 2.43 3.88 2.61 3.83 2.32 2.18 3.86 2.48 2.33 2.58 2.44 2.31 3.87
 2.21 2.52]


In [8]:
# fill missing values with mean column values
df_merge_data['GPA'].fillna(np.round(df_merge_data['GPA'].mean(),2), inplace=True)
print(df_merge_data['GPA'].unique())

[3.16 2.83 3.02 3.14 3.08 3.19 3.13 3.21 2.85 2.79 3.27 3.12 3.33 3.24
 3.71 3.03 2.82 2.89 3.65 3.25 3.56 3.59 3.1  2.73 3.09 3.5  2.76 2.78
 2.97 3.26 3.15 3.3  2.98 3.31 3.52 2.77 2.69 2.9  2.96 3.06 2.86 2.81
 3.58 2.62 3.23 2.93 3.54 2.91 3.01 3.32 3.   3.2  3.7  2.87 3.05 3.07
 3.17 3.62 3.04 3.37 3.64 3.22 3.28 3.11 2.64 2.95 2.68 3.46 2.71 3.53
 3.38 3.44 3.74 2.75 2.72 3.4  3.42 2.92 3.18 2.37 3.51 3.68 2.84 3.36
 3.34 3.45 3.41 3.57 3.39 3.35 3.43 3.29 3.49 2.8  3.67 3.47 3.55 3.48
 3.85 2.67 3.6  3.61 3.69 2.99 2.94 3.77 2.7  3.8  3.78 3.81 3.73 3.63
 2.88 3.79 3.9  3.66 3.82 2.66 2.6  2.74 3.91 2.59 2.57 3.75 3.76 2.53
 2.54 2.55 2.63 2.51 2.5  2.56 2.65 2.45 3.92 2.25 3.89 2.42 3.84 3.72
 2.43 3.88 2.61 3.83 2.32 2.18 3.86 2.48 2.33 2.58 2.44 2.31 3.87 2.21
 2.52]


# Achievement_above_100%_during3quartal

In [9]:
# count the number of NaN values in each column
print(df_merge_data['Achievement_above_100%_during3quartal'].isna().sum())

4736


In [10]:
print(df_merge_data['Achievement_above_100%_during3quartal'].unique())

[ 0.  1.  2. nan]


In [11]:
# fill missing values with median column values
df_merge_data['Achievement_above_100%_during3quartal'].fillna(df_merge_data['Achievement_above_100%_during3quartal'].median(), inplace=True)
print(df_merge_data['Achievement_above_100%_during3quartal'].unique())

[0. 1. 2.]


# assign_of_otherposition

In [12]:
print(df_merge_data['assign_of_otherposition'].unique())

[ 0.  1.  2. nan]


In [13]:
# fill missing values with median column values
df_merge_data['assign_of_otherposition'].fillna(df_merge_data['assign_of_otherposition'].median(), inplace=True)
print(df_merge_data['assign_of_otherposition'].unique())

[0. 1. 2.]


# job_duration_in_current_person_level

In [14]:
print(df_merge_data['job_duration_in_current_person_level'].unique())

[1.         1.11803399 1.22474487 1.25698051        nan 1.38564065
 1.15325626 1.47309199 1.08166538 1.2922848  1.35277493 1.5
 1.32287566 1.19163753 1.41421356 1.58113883 1.55563492 1.60623784
 1.44222051 1.03923048 1.52643375]


In [15]:
# fill missing values with mean column values
df_merge_data['job_duration_in_current_person_level'].fillna(np.round(df_merge_data['job_duration_in_current_person_level'].mean(),2), inplace=True)
print(df_merge_data['job_duration_in_current_person_level'].unique())

[1.         1.11803399 1.22474487 1.25698051 1.31       1.38564065
 1.15325626 1.47309199 1.08166538 1.2922848  1.35277493 1.5
 1.32287566 1.19163753 1.41421356 1.58113883 1.55563492 1.60623784
 1.44222051 1.03923048 1.52643375]


# sick_leaves

In [16]:
print(df_merge_data['sick_leaves'].unique())

[nan  0.  1.  2.]


In [17]:
# fill missing values with median column values
df_merge_data['sick_leaves'].fillna(df_merge_data['sick_leaves'].median(), inplace=True)
print(df_merge_data['sick_leaves'].unique())

[0. 1. 2.]


# job_duration_in_current_job_level

In [18]:
print(df_merge_data['job_duration_in_current_job_level'].unique())

[       nan 1.11803399 1.22474487 1.25698051 1.38564065 1.15325626
 1.47309199 1.08166538 1.58113883 1.2922848  1.35277493 1.5
 1.32287566 1.19163753 1.41421356 1.         1.44222051 1.55563492
 1.60623784 1.03923048 1.52643375 1.68226038 1.63401346 1.6583124
 0.9591663 ]


In [19]:
# fill missing values with mean column values
df_merge_data['job_duration_in_current_job_level'].fillna(np.round(df_merge_data['job_duration_in_current_job_level'].mean(),2), inplace=True)
print(df_merge_data['job_duration_in_current_job_level'].unique())

[1.31       1.11803399 1.22474487 1.25698051 1.38564065 1.15325626
 1.47309199 1.08166538 1.58113883 1.2922848  1.35277493 1.5
 1.32287566 1.19163753 1.41421356 1.         1.44222051 1.55563492
 1.60623784 1.03923048 1.52643375 1.68226038 1.63401346 1.6583124
 0.9591663 ]


# job_duration_from_training

In [21]:
print(df_merge_data['job_duration_from_training'].unique())

[nan  3.  2.  5.  6.  4.  7.  8. 10.]


In [22]:
# fill missing values with median column values
df_merge_data['job_duration_from_training'].fillna(df_merge_data['job_duration_from_training'].median(), inplace=True)
print(df_merge_data['job_duration_from_training'].unique())

[ 5.  3.  2.  6.  4.  7.  8. 10.]


# year_graduated

In [23]:
print(df_merge_data['year_graduated'].unique())

[34 12 33 14 17 36  8 28 15 37 32 35 10 11 27 30 29  3  7 13 20 19  4  9
 16  6 25 18 26 31 21 23 22  5 24  2 38 39  1]


In [24]:
# fill missing values with median column values
df_merge_data['year_graduated'].fillna(df_merge_data['year_graduated'].median(), inplace=True)
print(df_merge_data['year_graduated'].unique())

[34 12 33 14 17 36  8 28 15 37 32 35 10 11 27 30 29  3  7 13 20 19  4  9
 16  6 25 18 26 31 21 23 22  5 24  2 38 39  1]


# branch_rotation

In [25]:
print(df_merge_data['branch_rotation'].unique())

[nan  2.  5.  1.  4.  7.  6.  3.]


In [26]:
# fill missing values with median column values
df_merge_data['branch_rotation'].fillna(df_merge_data['branch_rotation'].median(), inplace=True)
print(df_merge_data['branch_rotation'].unique())

[3. 2. 5. 1. 4. 7. 6.]


# job_rotation

In [29]:
print(df_merge_data['job_rotation'].unique())

[ 6.  2.  7.  4.  3. nan  5.  1.]


In [30]:
# fill missing values with median column values
df_merge_data['job_rotation'].fillna(df_merge_data['job_rotation'].median(), inplace=True)
print(df_merge_data['job_rotation'].unique())

[6. 2. 7. 4. 3. 5. 1.]


# job_duration_in_current_branch

In [37]:
print(df_merge_data['job_duration_in_current_branch'].unique())

[1.38564065 0.41231056 1.22474487 1.15325626 1.11803399 1.5
 1.19163753 0.91104336 0.64807407 0.70710678 1.         1.82482876
 1.41421356 1.78044938 1.55563492 0.9591663  0.8660254  1.35277493
 1.8493242  0.         1.32287566 1.52643375 1.58113883 1.08166538
 0.5        0.81853528 1.60623784 1.87082869 1.47309199 1.25698051
 0.57445626 1.68226038 1.03923048 1.91572441 0.28284271 1.44222051
 1.2922848         nan 1.75499288 1.80277564 1.63401346 1.6583124
 2.         1.93649167 1.70880075 0.76157731 1.89208879 1.73205081
 1.95703858 1.97989899]


In [38]:
# fill missing values with mean column values
df_merge_data['job_duration_in_current_branch'].fillna(np.round(df_merge_data['job_duration_in_current_branch'].mean(),2), inplace=True)
print(df_merge_data['job_duration_in_current_branch'].unique())

[1.38564065 0.41231056 1.22474487 1.15325626 1.11803399 1.5
 1.19163753 0.91104336 0.64807407 0.70710678 1.         1.82482876
 1.41421356 1.78044938 1.55563492 0.9591663  0.8660254  1.35277493
 1.8493242  0.         1.32287566 1.52643375 1.58113883 1.08166538
 0.5        0.81853528 1.60623784 1.87082869 1.47309199 1.25698051
 0.57445626 1.68226038 1.03923048 1.91572441 0.28284271 1.44222051
 1.2922848  1.03       1.75499288 1.80277564 1.63401346 1.6583124
 2.         1.93649167 1.70880075 0.76157731 1.89208879 1.73205081
 1.95703858 1.97989899]


# annual leave

In [39]:
print(df_merge_data['annual leave'].unique())

[ 4.  3.  2.  0.  7.  5.  6.  1.  8. nan  9.]


In [40]:
# fill missing values with median column values
df_merge_data['annual leave'].fillna(df_merge_data['annual leave'].median(), inplace=True)
print(df_merge_data['annual leave'].unique())

[4. 3. 2. 0. 7. 5. 6. 1. 8. 9.]


# number_of_dependences

In [43]:
print(df_merge_data['number_of_dependences'].unique())

[ 2.  0.  3.  1.  4.  5. nan]


In [44]:
# fill missing values with median column values
df_merge_data['number_of_dependences'].fillna(df_merge_data['number_of_dependences'].median(), inplace=True)
print(df_merge_data['number_of_dependences'].unique())

[2. 0. 3. 1. 4. 5.]


# age

In [45]:
print(df_merge_data['age'].unique())

[54 30 32 35 55 47 33 53 56 52 28 45 48 58 51 50 31 34 42 36 41 29 37 27
 38 40 39 57 49 44 46 43 25 26 24]


In [46]:
# fill missing values with median column values
df_merge_data['age'].fillna(df_merge_data['age'].median(), inplace=True)
print(df_merge_data['age'].unique())

[54 30 32 35 55 47 33 53 56 52 28 45 48 58 51 50 31 34 42 36 41 29 37 27
 38 40 39 57 49 44 46 43 25 26 24]


In [48]:
df_train_new = df_merge_data.iloc[:len(df_train),:] 
df_test_new = df_merge_data.iloc[len(df_train):,:]

In [49]:
print(df_train_new.shape)
print(df_test_new.shape)

(19337, 22)
(6000, 22)


In [50]:
df_train_new.to_csv("5.complete_train.csv", index=False)
df_test_new.to_csv("5.complete_test.csv", index=False)